// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgeG3R4lKfTBEszoIPsHaYvNw2zslEozU',
    appId: '1:441992076502:web:3ff76889b7bc04b12f3d77',
    messagingSenderId: '441992076502',
    projectId: 'netflix-project-9760f',
    authDomain: 'netflix-project-9760f.firebaseapp.com',
    storageBucket: 'netflix-project-9760f.appspot.com',
    measurementId: 'G-4E9419GSJ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2zf8GLq-LUr-142_yYrSjCJqU-DEsACc',
    appId: '1:441992076502:android:c2405f264897219c2f3d77',
    messagingSenderId: '441992076502',
    projectId: 'netflix-project-9760f',
    storageBucket: 'netflix-project-9760f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAu6VWpJ8midb1Oq-tdXQVO6B6TnRci5qA',
    appId: '1:441992076502:ios:af3ad4f96c83d22f2f3d77',
    messagingSenderId: '441992076502',
    projectId: 'netflix-project-9760f',
    storageBucket: 'netflix-project-9760f.appspot.com',
    iosBundleId: 'com.example.weatherFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAu6VWpJ8midb1Oq-tdXQVO6B6TnRci5qA',
    appId: '1:441992076502:ios:af3ad4f96c83d22f2f3d77',
    messagingSenderId: '441992076502',
    projectId: 'netflix-project-9760f',
    storageBucket: 'netflix-project-9760f.appspot.com',
    iosBundleId: 'com.example.weatherFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgeG3R4lKfTBEszoIPsHaYvNw2zslEozU',
    appId: '1:441992076502:web:f5c82e98ea7d39b92f3d77',
    messagingSenderId: '441992076502',
    projectId: 'netflix-project-9760f',
    authDomain: 'netflix-project-9760f.firebaseapp.com',
    storageBucket: 'netflix-project-9760f.appspot.com',
    measurementId: 'G-0KX90MGCZW',
  );
}
